export enum CommandDefine {
    /**检查登录状态 */
    /**打开GatePanel */
    InitGatePanel = "InitGatePanel",
    GateCommand = "GateCommand",
    StartUp = "StartUp",
    AudioCommand = "AudioCommand",
    WebSocketReconnect = "WebSocketReconnect",
    CheckLoginState = "CheckLoginState",
    OpenLoginPanel = "OpenLoginPanel",
    OpenUpdatePromptAlert = "OpenUpdatePromptAlert",
    ShowHeaderPanel = "ShowHeaderPanel",
    OpenToast = "OpenToast",
    OpenDeskList = "OpenDeskList",
    /** 更新玩家金币 */
    UpdatePlayerGold = "UpdatePlayerGold",
    /** 更新昵称 */
    UpdateNickname = "UpdateNickname",
    UpdateHead = "UpdateHead",
    OpenPromptWindow = "OpenPromptWindow",
    InitGateMainPanel = "InitGateMainPanel",
    CloseLoginPanel = "CloseLoginPanel",
    OpenSetting = "OpenSetting",
    OpenExchangePanel = "OpenExchangePanel",
    OpenRecordPanel = "OpenRecordPanel",
    OpenRecordDetailList = "OpenRecordDetailList",
    OpenRecordAlter = "OpenRecordAlter",
    ChangeUser = "ChangeUser",
    OpenMyCenter = "OpenMyCenter",
    OpenShare = "OpenShare",
    OpenQYQPanel = "OpenQYQPanel",
    OpenGiveAwayPanel = "OpenGiveAwayPanel",
    OpenLoadingPanel = "OpenLoadingPanel",
    CloseLoadingPanel = "CloseLoadingPanel",
    /** 强制下线 */
    ForcedOffline = "ForcedOffline",
    UpdateUserStatus = "updateUserStatus",
    //牌桌
    /**更新玩家信息 */
    RefreshPlayerPush = "RefreshPlayer",
    /**初始化牌桌 */
    InitDeskPanel = "InitDeskPanel",
    /**发牌 */
    LicensingCardPush = "LicensingCardPush",
    /**摸牌 */
    GetGameCardPush = "GetGameCardPush",
    ExitDeskPanel = "ExitDeskPanel",
    ShowCardPush = "ShowCardPush",
    ShowCard = "ShowCard",
    ShowCardNotificationPush = "ShowCardNotificationPush",
    ShowMyEventPush = "ShowMyEventPush",
    EventDonePush = "EventDonePush",
    ShowCenterEffect = "ShowCenterEffect",
    ReStartGamePush = 'ReStartGamePush',
    ShowCardEffect = "ShowCardEffect",
    Entrust = "Entrust",
    EntrustNotice = "EntrustNotice",
    OpenEntrustPanel = "OpenEntrustPanel",
    OpenBonusIndex = "OpenBonusIndex",
    OpenChatBox = "OpenChatBox",
    ShowDeskChatMsg = "ShowDeskChatMsg",
    closeLoginPanel = "closeLoginPanel",
    OpenNoticeAlert = "OpenNoticeAlert",
    OpenPopupWindow = "OpenPopupWindow",
    OpenXzddRuleDetail = "OpenXzddRuleDetail",
    UpdateLeessang = "UpdateLeessang",
    ChangePlayerGold = "ChangePlayerGold",
    OpenMyPlayer = "OpenMyPlayer",
    OpenMyEnterPrise = "OpenMyEnterPrise",
    OpenBindSuperior = "OpenBindSuperior",
    OpenSetExchangePwd = "OpenSetExchangePwd",
    UpdateClubSimpleInfo = "UpdateClubSimpleInfo",
}