export enum ClubErrorCode {
    /** 成功 */
    SUCCEED = 0,
    /** 创建普通包间达到上限了 */
    CREATE_GENERAL_ROOM_LIMIT = 1001,
    /** token校验失败 */
    TOKEN_VERIFY_FAILED = 1002,
    /** 不是俱乐部成员 */
    NO_CLUB_MEMBER = 1003,
    /** 俱乐部不存在 */
    CLUB_NOT_EXIST = 1004,
    /** 创建俱乐部房间参数错误 */
    CREATE_ROOM_PARAM_ERROR = 1005,
    /** 已经加入俱乐部 */
    ALREADY_JOIN_CLUB = 1006,
    /** 房间不存在 */
    ROOM_NOT_EXIST = 1007,
    /** 无权限 */
    NOT_POWER = 1008,
    /** 俱乐部打烊了 */
    CLUB_CLOSING = 1009,
    /** 老板钻石不足 */
    BOSS_DIAMOND_LACK = 1010,
    /** 自己的钻石不足 */
    MY_DIAMOND_LACK = 1011,
    /** 系统维护中 */
    SYSTEM_MAINTAIN = 1012,
    /** 没有可用位置了 */
    NOT_SEAT = 1013,
	/** 禁止玩游戏 */
	FORBID_GAME = 1014,
}