export enum GameServerCode {
    /** 成功 */
    SUCCEED = 0,
    /** 用户锁定 */
    PLAYER_LOCK = 1,
    /** 用户超过最大可赢点数 */
    PLAYER_MAX_MONEY = 2,
    /** 用户不存在 */
    PLAYER_NONENTITY = 3,
    /** 服务器维护 */
    SERVER_MAINTAIN = 5,
    /** TOKEN验证失败 */
    TOKEN_VERIFY_FAIL = 6,
    /** 服务器发生异常 */
    SERVER_EXCEPTION = 7,
    /** 用户登录重复 */
    PLAYER_LOGIN_REPEAT = 12,
    /** 重复消息 */
    REPEAT_MESSAGE = 13,
    /** 从未玩过游戏 */
    ALWAYS_PLAY_GAME = 28,
    /** 座位占用了 */
    POSITION_OCCUPY = 31,
    /** 房间不存在 */
    ROOM_NOT_EXIST = 34,
    /** 低于离场限制 */
    UNDER_LEAVE_LIMIT = 38,
    /** 未准备踢出房间 */
    NOT_READY_KICK_OUT_ROOM = 39,
    /** 此房间不能中途加入 */
    NOT_MIDWAY_JOIN_DESK = 41,
    /** 玩家禁止加入游戏 */
    PLAYER_BAN_JOIN_GAME = 42,
    /** 玩家禁止参与俱乐部游戏 */
    PLAYER_BAN_CLUB_GAME = 43,
}